version: "3.8"

services:
  mongo:
    image: mongo:4.4
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"

  fastapi:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGO_CONNECTION_STRING=mongodb+srv://foultrip:futbol03@cluster0.zvglw0r.mongodb.net/
    depends_on:
      - mongo