version: "3.8"

services:
  mongo:
    image: mongo:4.4
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"

  fastapi:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongo